version: '2'
services:

  comments:
    extends:
      file: docker-compose.common.yml
      service: base
    ports:
      - "8080:8080"
    command:
      - 'dockerize'
      - '-wait'
      - 'tcp://db:5432'
      - 'python'
      - 'core/main.py'
    depends_on:
      - db

  db:
    build: dbtools
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: dmishin
      POSTGRES_PASSWORD: dmishin
      POSTGRES_DB: comments_db
