DROP TYPE IF EXISTS ancestor_type CASCADE;
DROP TYPE IF EXISTS action_type CASCADE;
DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS entities CASCADE;
DROP TABLE IF EXISTS history CASCADE;
DROP TRIGGER IF EXISTS tr_create_comment ON entities CASCADE;
DROP TRIGGER IF EXISTS tr_update_comment ON entities CASCADE;
DROP TABLE IF EXISTS search_history CASCADE;
